/* Generated by build-docs.mjs — do not edit by hand. */
window.DOCS_NAV = [
  {
    "section": "Documentation",
    "links": [
      {
        "href": "index.html",
        "label": "Overview"
      }
    ]
  },
  {
    "section": "Learn",
    "links": [
      {
        "href": "m-slm-architectures.html",
        "label": "SLM architectures"
      },
      {
        "href": "m-fine-tuning.html",
        "label": "Fine-tuning techniques"
      },
      {
        "href": "m-taxonomy.html",
        "label": "Safety taxonomy"
      }
    ]
  },
  {
    "section": "Studio & workflow",
    "links": [
      {
        "href": "m-workflow.html",
        "label": "Guided workflow"
      },
      {
        "href": "m-datasets.html",
        "label": "Datasets"
      }
    ]
  },
  {
    "section": "Benchmarks & results",
    "links": [
      {
        "href": "m-benchmarks.html",
        "label": "Benchmark suite"
      },
      {
        "href": "m-ensembles.html",
        "label": "Ensembles"
      }
    ]
  },
  {
    "section": "Architecture",
    "links": [
      {
        "href": "m-architecture.html",
        "label": "System architecture"
      }
    ]
  },
  {
    "section": "Roadmap",
    "links": [
      {
        "href": "m-roadmap.html",
        "label": "Roadmap"
      }
    ]
  }
];
