#!/usr/bin/env python
"""Render studies/README.md and papers/README.md from the registry.

These files are generated, never hand-edited: the layout plan requires the registry to
be the only source of study state. `--check` fails when a rendered file has drifted,
so CI can enforce that without a human remembering to regenerate.

Usage:
    python tools/render_indexes.py            # write
    python tools/render_indexes.py --check    # fail if stale
"""
from __future__ import annotations

import argparse
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
BANNER = "<!-- GENERATED by tools/render_indexes.py from studies/registry.yaml. Do not edit. -->"

STATE_MARK = {
    "released": "released", "active": "active", "stopped": "stopped",
    "blocked": "blocked", "contract_drifted": "contract-drifted",
    "superseded": "superseded", "protocol_candidate": "protocol candidate",
    "development_only": "development only", "invalidated": "invalidated",
}


def load():
    import yaml
    return yaml.safe_load((ROOT / "studies/registry.yaml").read_text())


def studies_index(reg) -> str:
    lines = [BANNER, "", "# Studies", "",
             "Normative source: [`studies/registry.yaml`](registry.yaml), validated by",
             "[`registry.schema.json`](registry.schema.json). Run `make check-registry`.", "",
             f"Registry `{reg['registry_id']}` last verified at "
             f"`{reg['last_verified']['git_revision']}` on {reg['last_verified']['date']}"
             f"{' (dirty tree)' if reg['last_verified']['dirty_tree'] else ''}.", "",
             "## State", "",
             "| Study | State | Evidence | Claims? | Contract | Verification |",
             "| --- | --- | --- | --- | --- | --- |"]
    for s in reg["studies"]:
        claims = "**yes**" if s["claim_authorization"] else "no"
        exp = s["expected_verification_status"].replace("_", " ")
        lines.append(
            f"| `{s['study_id']}` | {STATE_MARK.get(s['study_state'], s['study_state'])} "
            f"| {s['evidence_state'].replace('_', ' ')} | {claims} "
            f"| {s['contract_type'].replace('_', ' ')} | {exp} |"
        )

    lines += ["", "## Declared verification failures", "",
              "A historical lock is *expected* to fail against an evolved tree. Declaring that",
              "is how a real regression stops hiding behind a known one.", ""]
    any_fail = False
    for s in reg["studies"]:
        if s["expected_verification_status"] == "expected_fail":
            any_fail = True
            reason = " ".join((s.get("verification_failure_reason") or "").split())
            lines += [f"**`{s['study_id']}`** — `{s.get('verification_command')}`", "",
                      f"> {reason}", ""]
    if not any_fail:
        lines.append("_None._")

    lines += ["", "## Lineage", ""]
    for s in reg["studies"]:
        edges = []
        if s.get("predecessor"):
            edges.append(f"after `{s['predecessor']}`")
        if s.get("successor"):
            edges.append(f"before `{s['successor']}`")
        if s.get("supersedes"):
            edges.append("supersedes " + ", ".join(f"`{x}`" for x in s["supersedes"]))
        if s.get("consumes"):
            edges.append("consumes " + ", ".join(f"`{x}`" for x in s["consumes"]))
        if edges:
            lines.append(f"- `{s['study_id']}` — {'; '.join(edges)}")

    lines += ["", "## Distribution", "",
              "Every source's redistribution decision lives in",
              "[`benchmarks/registry/distribution.yaml`](../benchmarks/registry/distribution.yaml).",
              "No source is currently approved for `publish_text`.", ""]
    for s in reg["studies"]:
        if s["distribution_state"] in ("unresolved", "local_only"):
            lines.append(f"- `{s['study_id']}` — {s['distribution_state'].replace('_', ' ')}")
    return "\n".join(lines) + "\n"


def papers_index(reg) -> str:
    lines = [BANNER, "", "# Publications", "",
             "Publication state comes from [`studies/registry.yaml`](../studies/registry.yaml);",
             "this file is a generated view. A document under `papers/` is not automatically",
             "current — the label below is authoritative.", "",
             "| Manuscript | Study | Publication state | Evidence tier |",
             "| --- | --- | --- | --- |"]
    for s in reg["studies"]:
        for path in s.get("manuscript_paths") or []:
            rel = path[len("papers/"):] if path.startswith("papers/") else f"../{path}"
            tier = " ".join(s["evidence_tier"].split())
            lines.append(
                f"| [`{path}`]({rel}) | `{s['study_id']}` "
                f"| {s['publication_state']} | {tier} |"
            )
    lines += ["", "## Editorial lifecycle", "",
              "- `unified-report/proposal.md` is a contract-consumed starting-type protocol",
              "  despite its generic filename; it stays at its current path.",
              "- `unified-report/review.md` is the latest scientific review.",
              "- `unified-report/review-2026-07-17.md` is a historical applied-fix ledger.",
              "- Simplified editions are editorial derivatives, not separate studies.",
              "- Office `~$` lock files are not publication artifacts and are git-ignored.", ""]
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    reg = load()
    targets = {ROOT / "studies/README.md": studies_index(reg),
               ROOT / "papers/README.md": papers_index(reg)}
    stale = []
    for path, content in targets.items():
        if args.check:
            current = path.read_text() if path.is_file() else ""
            if current != content:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.write_text(content)
            print(f"wrote {path.relative_to(ROOT)}")
    if stale:
        print("ERROR stale generated index: " + ", ".join(stale))
        print("      run: python tools/render_indexes.py")
        return 1
    if args.check:
        print("generated indexes are current")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
